spring:
  datasource:
    url: jdbc:mysql://localhost:3306/information_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: alan
    password: password
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

server:
  port: 3000
file:
  dir: src/main/resources/static/images
